//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PSUPKTProvider.PSUPKTPassportService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PSUPKTPassportService.AuthenticationSoap")]
    public interface AuthenticationSoap {
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Authenticate", ReplyAction="*")]
        PSUPKTProvider.PSUPKTPassportService.AuthenticateResponse Authenticate(PSUPKTProvider.PSUPKTPassportService.AuthenticateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Authenticate", ReplyAction="*")]
        System.Threading.Tasks.Task<PSUPKTProvider.PSUPKTPassportService.AuthenticateResponse> AuthenticateAsync(PSUPKTProvider.PSUPKTPassportService.AuthenticateRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStudentDetails", ReplyAction="*")]
        PSUPKTProvider.PSUPKTPassportService.GetStudentDetailsResponse GetStudentDetails(PSUPKTProvider.PSUPKTPassportService.GetStudentDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStudentDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<PSUPKTProvider.PSUPKTPassportService.GetStudentDetailsResponse> GetStudentDetailsAsync(PSUPKTProvider.PSUPKTPassportService.GetStudentDetailsRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStaffDetails", ReplyAction="*")]
        PSUPKTProvider.PSUPKTPassportService.GetStaffDetailsResponse GetStaffDetails(PSUPKTProvider.PSUPKTPassportService.GetStaffDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStaffDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<PSUPKTProvider.PSUPKTPassportService.GetStaffDetailsResponse> GetStaffDetailsAsync(PSUPKTProvider.PSUPKTPassportService.GetStaffDetailsRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserDetails", ReplyAction="*")]
        PSUPKTProvider.PSUPKTPassportService.GetUserDetailsResponse GetUserDetails(PSUPKTProvider.PSUPKTPassportService.GetUserDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUserDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<PSUPKTProvider.PSUPKTPassportService.GetUserDetailsResponse> GetUserDetailsAsync(PSUPKTProvider.PSUPKTPassportService.GetUserDetailsRequest request);
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStaffID", ReplyAction="*")]
        PSUPKTProvider.PSUPKTPassportService.GetStaffIDResponse GetStaffID(PSUPKTProvider.PSUPKTPassportService.GetStaffIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStaffID", ReplyAction="*")]
        System.Threading.Tasks.Task<PSUPKTProvider.PSUPKTPassportService.GetStaffIDResponse> GetStaffIDAsync(PSUPKTProvider.PSUPKTPassportService.GetStaffIDRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthenticateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Authenticate", Namespace="http://tempuri.org/", Order=0)]
        public PSUPKTProvider.PSUPKTPassportService.AuthenticateRequestBody Body;
        
        public AuthenticateRequest() {
        }
        
        public AuthenticateRequest(PSUPKTProvider.PSUPKTPassportService.AuthenticateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthenticateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public AuthenticateRequestBody() {
        }
        
        public AuthenticateRequestBody(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthenticateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AuthenticateResponse", Namespace="http://tempuri.org/", Order=0)]
        public PSUPKTProvider.PSUPKTPassportService.AuthenticateResponseBody Body;
        
        public AuthenticateResponse() {
        }
        
        public AuthenticateResponse(PSUPKTProvider.PSUPKTPassportService.AuthenticateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthenticateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AuthenticateResult;
        
        public AuthenticateResponseBody() {
        }
        
        public AuthenticateResponseBody(bool AuthenticateResult) {
            this.AuthenticateResult = AuthenticateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStudentDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStudentDetails", Namespace="http://tempuri.org/", Order=0)]
        public PSUPKTProvider.PSUPKTPassportService.GetStudentDetailsRequestBody Body;
        
        public GetStudentDetailsRequest() {
        }
        
        public GetStudentDetailsRequest(PSUPKTProvider.PSUPKTPassportService.GetStudentDetailsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStudentDetailsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public GetStudentDetailsRequestBody() {
        }
        
        public GetStudentDetailsRequestBody(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStudentDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStudentDetailsResponse", Namespace="http://tempuri.org/", Order=0)]
        public PSUPKTProvider.PSUPKTPassportService.GetStudentDetailsResponseBody Body;
        
        public GetStudentDetailsResponse() {
        }
        
        public GetStudentDetailsResponse(PSUPKTProvider.PSUPKTPassportService.GetStudentDetailsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStudentDetailsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PSUPKTProvider.PSUPKTPassportService.ArrayOfString GetStudentDetailsResult;
        
        public GetStudentDetailsResponseBody() {
        }
        
        public GetStudentDetailsResponseBody(PSUPKTProvider.PSUPKTPassportService.ArrayOfString GetStudentDetailsResult) {
            this.GetStudentDetailsResult = GetStudentDetailsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStaffDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStaffDetails", Namespace="http://tempuri.org/", Order=0)]
        public PSUPKTProvider.PSUPKTPassportService.GetStaffDetailsRequestBody Body;
        
        public GetStaffDetailsRequest() {
        }
        
        public GetStaffDetailsRequest(PSUPKTProvider.PSUPKTPassportService.GetStaffDetailsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStaffDetailsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public GetStaffDetailsRequestBody() {
        }
        
        public GetStaffDetailsRequestBody(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStaffDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStaffDetailsResponse", Namespace="http://tempuri.org/", Order=0)]
        public PSUPKTProvider.PSUPKTPassportService.GetStaffDetailsResponseBody Body;
        
        public GetStaffDetailsResponse() {
        }
        
        public GetStaffDetailsResponse(PSUPKTProvider.PSUPKTPassportService.GetStaffDetailsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStaffDetailsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PSUPKTProvider.PSUPKTPassportService.ArrayOfString GetStaffDetailsResult;
        
        public GetStaffDetailsResponseBody() {
        }
        
        public GetStaffDetailsResponseBody(PSUPKTProvider.PSUPKTPassportService.ArrayOfString GetStaffDetailsResult) {
            this.GetStaffDetailsResult = GetStaffDetailsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserDetails", Namespace="http://tempuri.org/", Order=0)]
        public PSUPKTProvider.PSUPKTPassportService.GetUserDetailsRequestBody Body;
        
        public GetUserDetailsRequest() {
        }
        
        public GetUserDetailsRequest(PSUPKTProvider.PSUPKTPassportService.GetUserDetailsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserDetailsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public GetUserDetailsRequestBody() {
        }
        
        public GetUserDetailsRequestBody(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUserDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUserDetailsResponse", Namespace="http://tempuri.org/", Order=0)]
        public PSUPKTProvider.PSUPKTPassportService.GetUserDetailsResponseBody Body;
        
        public GetUserDetailsResponse() {
        }
        
        public GetUserDetailsResponse(PSUPKTProvider.PSUPKTPassportService.GetUserDetailsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUserDetailsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public PSUPKTProvider.PSUPKTPassportService.ArrayOfString GetUserDetailsResult;
        
        public GetUserDetailsResponseBody() {
        }
        
        public GetUserDetailsResponseBody(PSUPKTProvider.PSUPKTPassportService.ArrayOfString GetUserDetailsResult) {
            this.GetUserDetailsResult = GetUserDetailsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStaffIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStaffID", Namespace="http://tempuri.org/", Order=0)]
        public PSUPKTProvider.PSUPKTPassportService.GetStaffIDRequestBody Body;
        
        public GetStaffIDRequest() {
        }
        
        public GetStaffIDRequest(PSUPKTProvider.PSUPKTPassportService.GetStaffIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStaffIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public GetStaffIDRequestBody() {
        }
        
        public GetStaffIDRequestBody(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStaffIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStaffIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public PSUPKTProvider.PSUPKTPassportService.GetStaffIDResponseBody Body;
        
        public GetStaffIDResponse() {
        }
        
        public GetStaffIDResponse(PSUPKTProvider.PSUPKTPassportService.GetStaffIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStaffIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetStaffIDResult;
        
        public GetStaffIDResponseBody() {
        }
        
        public GetStaffIDResponseBody(string GetStaffIDResult) {
            this.GetStaffIDResult = GetStaffIDResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AuthenticationSoapChannel : PSUPKTProvider.PSUPKTPassportService.AuthenticationSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuthenticationSoapClient : System.ServiceModel.ClientBase<PSUPKTProvider.PSUPKTPassportService.AuthenticationSoap>, PSUPKTProvider.PSUPKTPassportService.AuthenticationSoap {
        
        public AuthenticationSoapClient() {
        }
        
        public AuthenticationSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AuthenticationSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthenticationSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthenticationSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PSUPKTProvider.PSUPKTPassportService.AuthenticateResponse PSUPKTProvider.PSUPKTPassportService.AuthenticationSoap.Authenticate(PSUPKTProvider.PSUPKTPassportService.AuthenticateRequest request) {
            return base.Channel.Authenticate(request);
        }
        
        public bool Authenticate(string username, string password) {
            PSUPKTProvider.PSUPKTPassportService.AuthenticateRequest inValue = new PSUPKTProvider.PSUPKTPassportService.AuthenticateRequest();
            inValue.Body = new PSUPKTProvider.PSUPKTPassportService.AuthenticateRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            PSUPKTProvider.PSUPKTPassportService.AuthenticateResponse retVal = ((PSUPKTProvider.PSUPKTPassportService.AuthenticationSoap)(this)).Authenticate(inValue);
            return retVal.Body.AuthenticateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PSUPKTProvider.PSUPKTPassportService.AuthenticateResponse> PSUPKTProvider.PSUPKTPassportService.AuthenticationSoap.AuthenticateAsync(PSUPKTProvider.PSUPKTPassportService.AuthenticateRequest request) {
            return base.Channel.AuthenticateAsync(request);
        }
        
        public System.Threading.Tasks.Task<PSUPKTProvider.PSUPKTPassportService.AuthenticateResponse> AuthenticateAsync(string username, string password) {
            PSUPKTProvider.PSUPKTPassportService.AuthenticateRequest inValue = new PSUPKTProvider.PSUPKTPassportService.AuthenticateRequest();
            inValue.Body = new PSUPKTProvider.PSUPKTPassportService.AuthenticateRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((PSUPKTProvider.PSUPKTPassportService.AuthenticationSoap)(this)).AuthenticateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PSUPKTProvider.PSUPKTPassportService.GetStudentDetailsResponse PSUPKTProvider.PSUPKTPassportService.AuthenticationSoap.GetStudentDetails(PSUPKTProvider.PSUPKTPassportService.GetStudentDetailsRequest request) {
            return base.Channel.GetStudentDetails(request);
        }
        
        public PSUPKTProvider.PSUPKTPassportService.ArrayOfString GetStudentDetails(string username, string password) {
            PSUPKTProvider.PSUPKTPassportService.GetStudentDetailsRequest inValue = new PSUPKTProvider.PSUPKTPassportService.GetStudentDetailsRequest();
            inValue.Body = new PSUPKTProvider.PSUPKTPassportService.GetStudentDetailsRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            PSUPKTProvider.PSUPKTPassportService.GetStudentDetailsResponse retVal = ((PSUPKTProvider.PSUPKTPassportService.AuthenticationSoap)(this)).GetStudentDetails(inValue);
            return retVal.Body.GetStudentDetailsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PSUPKTProvider.PSUPKTPassportService.GetStudentDetailsResponse> PSUPKTProvider.PSUPKTPassportService.AuthenticationSoap.GetStudentDetailsAsync(PSUPKTProvider.PSUPKTPassportService.GetStudentDetailsRequest request) {
            return base.Channel.GetStudentDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<PSUPKTProvider.PSUPKTPassportService.GetStudentDetailsResponse> GetStudentDetailsAsync(string username, string password) {
            PSUPKTProvider.PSUPKTPassportService.GetStudentDetailsRequest inValue = new PSUPKTProvider.PSUPKTPassportService.GetStudentDetailsRequest();
            inValue.Body = new PSUPKTProvider.PSUPKTPassportService.GetStudentDetailsRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((PSUPKTProvider.PSUPKTPassportService.AuthenticationSoap)(this)).GetStudentDetailsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PSUPKTProvider.PSUPKTPassportService.GetStaffDetailsResponse PSUPKTProvider.PSUPKTPassportService.AuthenticationSoap.GetStaffDetails(PSUPKTProvider.PSUPKTPassportService.GetStaffDetailsRequest request) {
            return base.Channel.GetStaffDetails(request);
        }
        
        public PSUPKTProvider.PSUPKTPassportService.ArrayOfString GetStaffDetails(string username, string password) {
            PSUPKTProvider.PSUPKTPassportService.GetStaffDetailsRequest inValue = new PSUPKTProvider.PSUPKTPassportService.GetStaffDetailsRequest();
            inValue.Body = new PSUPKTProvider.PSUPKTPassportService.GetStaffDetailsRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            PSUPKTProvider.PSUPKTPassportService.GetStaffDetailsResponse retVal = ((PSUPKTProvider.PSUPKTPassportService.AuthenticationSoap)(this)).GetStaffDetails(inValue);
            return retVal.Body.GetStaffDetailsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PSUPKTProvider.PSUPKTPassportService.GetStaffDetailsResponse> PSUPKTProvider.PSUPKTPassportService.AuthenticationSoap.GetStaffDetailsAsync(PSUPKTProvider.PSUPKTPassportService.GetStaffDetailsRequest request) {
            return base.Channel.GetStaffDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<PSUPKTProvider.PSUPKTPassportService.GetStaffDetailsResponse> GetStaffDetailsAsync(string username, string password) {
            PSUPKTProvider.PSUPKTPassportService.GetStaffDetailsRequest inValue = new PSUPKTProvider.PSUPKTPassportService.GetStaffDetailsRequest();
            inValue.Body = new PSUPKTProvider.PSUPKTPassportService.GetStaffDetailsRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((PSUPKTProvider.PSUPKTPassportService.AuthenticationSoap)(this)).GetStaffDetailsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PSUPKTProvider.PSUPKTPassportService.GetUserDetailsResponse PSUPKTProvider.PSUPKTPassportService.AuthenticationSoap.GetUserDetails(PSUPKTProvider.PSUPKTPassportService.GetUserDetailsRequest request) {
            return base.Channel.GetUserDetails(request);
        }
        
        public PSUPKTProvider.PSUPKTPassportService.ArrayOfString GetUserDetails(string username, string password) {
            PSUPKTProvider.PSUPKTPassportService.GetUserDetailsRequest inValue = new PSUPKTProvider.PSUPKTPassportService.GetUserDetailsRequest();
            inValue.Body = new PSUPKTProvider.PSUPKTPassportService.GetUserDetailsRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            PSUPKTProvider.PSUPKTPassportService.GetUserDetailsResponse retVal = ((PSUPKTProvider.PSUPKTPassportService.AuthenticationSoap)(this)).GetUserDetails(inValue);
            return retVal.Body.GetUserDetailsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PSUPKTProvider.PSUPKTPassportService.GetUserDetailsResponse> PSUPKTProvider.PSUPKTPassportService.AuthenticationSoap.GetUserDetailsAsync(PSUPKTProvider.PSUPKTPassportService.GetUserDetailsRequest request) {
            return base.Channel.GetUserDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<PSUPKTProvider.PSUPKTPassportService.GetUserDetailsResponse> GetUserDetailsAsync(string username, string password) {
            PSUPKTProvider.PSUPKTPassportService.GetUserDetailsRequest inValue = new PSUPKTProvider.PSUPKTPassportService.GetUserDetailsRequest();
            inValue.Body = new PSUPKTProvider.PSUPKTPassportService.GetUserDetailsRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((PSUPKTProvider.PSUPKTPassportService.AuthenticationSoap)(this)).GetUserDetailsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PSUPKTProvider.PSUPKTPassportService.GetStaffIDResponse PSUPKTProvider.PSUPKTPassportService.AuthenticationSoap.GetStaffID(PSUPKTProvider.PSUPKTPassportService.GetStaffIDRequest request) {
            return base.Channel.GetStaffID(request);
        }
        
        public string GetStaffID(string username, string password) {
            PSUPKTProvider.PSUPKTPassportService.GetStaffIDRequest inValue = new PSUPKTProvider.PSUPKTPassportService.GetStaffIDRequest();
            inValue.Body = new PSUPKTProvider.PSUPKTPassportService.GetStaffIDRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            PSUPKTProvider.PSUPKTPassportService.GetStaffIDResponse retVal = ((PSUPKTProvider.PSUPKTPassportService.AuthenticationSoap)(this)).GetStaffID(inValue);
            return retVal.Body.GetStaffIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<PSUPKTProvider.PSUPKTPassportService.GetStaffIDResponse> PSUPKTProvider.PSUPKTPassportService.AuthenticationSoap.GetStaffIDAsync(PSUPKTProvider.PSUPKTPassportService.GetStaffIDRequest request) {
            return base.Channel.GetStaffIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<PSUPKTProvider.PSUPKTPassportService.GetStaffIDResponse> GetStaffIDAsync(string username, string password) {
            PSUPKTProvider.PSUPKTPassportService.GetStaffIDRequest inValue = new PSUPKTProvider.PSUPKTPassportService.GetStaffIDRequest();
            inValue.Body = new PSUPKTProvider.PSUPKTPassportService.GetStaffIDRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((PSUPKTProvider.PSUPKTPassportService.AuthenticationSoap)(this)).GetStaffIDAsync(inValue);
        }
    }
}
